version: 2.1

jobs:
  update_readme_hacktoberfest:
    docker:
      - image: cimg/ruby:2.6
    steps:
      - checkout
      - run:
          command: |
            cd scripts
            gem install bundler:1.17.3
            bundle
            ./repos.rb > README-HACKTOBERFEST.md

workflows:
  update:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update_readme_hacktoberfest
